version: "3.9"

services:
  db:
    image: postgres:17
    container_name: ecompointer-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ecompointer
      POSTGRES_PASSWORD: ecompointer
      POSTGRES_DB: ecompointer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
